[package]
name = "codspeed"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"

[dev-dependencies]
criterion = { version = "2.7.2", package = "codspeed-criterion-compat" }

#![feature(portable_simd)]